spring:
  datasource:
    url: jdbc:sqlserver://kanbandbdynasty.database.windows.net:1433;database=ddkanbandb;user=kanbanboard@kanbandbdynasty;password=Devdynasty1!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
